### ISSUE TITLE
Short Cut to Scheduled Transaction Editor

### ISSUE THREAD

**Issue by pjridge** [codinguser/gnucash#1]
To edit existing scheduled transactions, I have to click Actions, Scheduled Transactions, Scheduled Transaction Editor. Would love to have a one-click icon to open the Scheduled Transaction Editor

**Comment by codinguser** [comment]
Sorry again, I don't work on desktop GnuCash. This is just my clone of the code. 
I believe this is the droid (bug-tracker) you are looking for: 
https://bugzilla.gnome.org/page.cgi?id=browse.html&product=GnuCash
